CREATE DATABASE crystal;
-- GRANT ALL PRIVILEGES ON mydb.* TO 'myuser'@'%' IDENTIFIED BY 'mysql';
-- GRANT ALL PRIVILEGES ON mydb.* TO 'myuser'@'localhost' IDENTIFIED BY 'mysql';
USE crystal;

CREATE TABLE equity_historical(
`id` INT NOT NULL AUTO_INCREMENT,
`date` DATE NOT NULL DEFAULT '1993-04-01',
`exchange` VARCHAR(5) NOT NULL DEFAULT 'na',
`symbol` VARCHAR(60) NOT NULL DEFAULT 'na',
`series` VARCHAR(5) NOT NULL DEFAULT 'na',
`close_pre` FLOAT NOT NULL DEFAULT 0,
`open` FLOAT NOT NULL DEFAULT 0,
`high` FLOAT NOT NULL DEFAULT 0,
`low` FLOAT NOT NULL DEFAULT 0,
`last` FLOAT NOT NULL DEFAULT 0,
`close` FLOAT NOT NULL DEFAULT 0,
`vwap` FLOAT NOT NULL DEFAULT 0,
`volume` INT NOT NULL DEFAULT 0,
`turnover` FLOAT NOT NULL DEFAULT 0,
`trades` INT NOT NULL DEFAULT 0,
`vol_deliverable` INT NOT NULL DEFAULT 0,
`vol_deliverable%` FLOAT NOT NULL DEFAULT 0,
PRIMARY KEY (`id`));

CREATE TABLE index_historical(
`id` INT NOT NULL AUTO_INCREMENT,
`date` DATE NOT NULL DEFAULT '1993-04-01',
`symbol` VARCHAR(60) NOT NULL DEFAULT 'na',
`open` FLOAT NOT NULL DEFAULT 0,
`high` FLOAT NOT NULL DEFAULT 0,
`low` FLOAT NOT NULL DEFAULT 0,
`close` FLOAT NOT NULL DEFAULT 0,
`turnover` FLOAT NOT NULL DEFAULT 0,
PRIMARY KEY (`id`));

CREATE TABLE news (
`id` INT NOT NULL AUTO_INCREMENT,
`datetime_ist` DATETIME NOT NULL DEFAULT '2020-01-01 00:00:00',
`source` VARCHAR(45) NOT NULL DEFAULT 'na',
`title` VARCHAR(60) NOT NULL DEFAULT 'na',
`description` LONGTEXT NOT NULL,
`link_article` TINYTEXT NOT NULL,
`link_image` TINYTEXT NOT NULL,
`catogeory` VARCHAR(45) NOT NULL DEFAULT 'na',
PRIMARY KEY (`id`));

CREATE TABLE symbol_metadata (
`id` INT NOT NULL AUTO_INCREMENT,
`type` VARCHAR(6) NULL DEFAULT 'na',
`symbol` VARCHAR(60) NULL DEFAULT 'na',
`name` VARCHAR(100) NULL DEFAULT 'na',
`sector` VARCHAR(45) NULL DEFAULT 'na',
`fo` VARCHAR(5) NULL DEFAULT 'false',
PRIMARY KEY (`id`));